### ISSUE TITLE
Location of SQLite file should be configurable

### ISSUE THREAD

**Issue by hffmnn** [ziminji/objective-c-sql-query-builder#1]
Hello ziminji,

today I had time to test your wrapper and I am very impressed. Works perfectly out of the box.
But one issue remains: You write in your feature list: 
_Automatically places the SQLite database in the "Document" directory._

I think, this should be configurable by the user, because an app may be rejected by Apple, if the database does not contain user generated content and is placed in Documents directory. So a static, readonly database should not be copied or e.g. copied to Caches directory.

What do you think?

Regards,
sunatmidnight

**Comment by ziminji** [comment]
Good point.....I never thought about it that way before.  I will look at adding an additional key/value to the plist to accommodate read-only databases.

**Comment by ziminji** [comment]
I have added a key/value to the plist and modified the connection class to now allow for read-only databases.  The new key/value in the plist is:

```
<key>readonly</key>
<false/>
```

Thanks for the suggestion...keep 'em coming....

**Comment by hffmnn** [comment]
Great, thanks a lot
