### ISSUE TITLE
left join syntax with ZIMSqlSelectStatement?

### ISSUE THREAD

**Issue by Sylva1n** [ziminji/objective-c-sql-query-builder#17]
Hello,

may someone post an example of code translating this Sql query into a ZIMSqlSelectStatement?

SELECT [t1].[id], [t1].[name] 
FROM [t1] LEFT JOIN [t2] ON [t2].[id] = [t1].[id]
WHERE [t2].[id] IS NULL;

thanks,

Sylvain

**Comment by ziminji** [comment]
Here you go:

```
ZIMSqlSelectStatement *sql = [[ZIMSqlSelectStatement alloc] init];
[sql column: @"t1.id"];
[sql column: @"t1.name"];
[sql from: @"t1"];
[sql join: @"t2"];
[sql joinOn: @"t2.id" operator: ZIMSqlOperatorEqualTo value: @"t1.id"];
[sql where: @"t2.id" operator: ZIMSqlOperatorEqualTo value: nil];
NSString *statement = [sql statement];
NSLog(@"%@", statement);
```

See, the [tutorial](https://github.com/ziminji/objective-c-sql-query-builder/wiki/CRUD-Operations) on the Wiki for more information.
