### ISSUE TITLE
Question about transaction and the ORM

### ISSUE THREAD

**Issue by Sylva1n** [ziminji/objective-c-sql-query-builder#18]
Hello,

Is there a way to encapsulate into a transaction several ORM operations?

For example:

Start transaction

Person *person = [[Person alloc] init];
[person setFirstName: @"John"];
[person setLastName: @"Doe"];
[person setIsActive: [NSNumber numberWithInt: 1]];
[person save];

Person *anotherPerson = [[Person alloc] init];
[anotherPerson setFirstName: @"Max"];
[anotherPerson setLastName: @"Cady"];
[anotherPerson setIsActive: [NSNumber numberWithInt: 1]];
[anotherPerson save];

Commit

Best regards,

Sylvain

**Comment by ziminji** [comment]
At the moment, it is not yet possible.  But if you would like to submit a solution, I would happy to look into implementing it.
