### ISSUE TITLE
build on xcode5 / 64-bit shows many clang issues where should use unsigned long instead of int

### ISSUE THREAD

**Issue by alexbbrown** [ziminji/objective-c-sql-query-builder#25]
Warnings such as: 

Implicit value loses integer precision

and 

values of type 'NSUInteger' should not be used as format arguments; add an explicit case to 'unsigned long' instead.

**Comment by ziminji** [comment]
In which file(s) (and line numbers) do you receive these warnings?  Can you post an example so that I update the code?
