### ISSUE TITLE
Xcode application which uses objective-c-sql-query-builder?

### ISSUE THREAD

**Issue by Bhushan30** [ziminji/objective-c-sql-query-builder#26]
How to use objective-c-sql-query-builder in cocoa application?
Can u please provide any link..

**Comment by ziminji** [comment]
Just copy the .h and .m files in the "src" folder to your Xcode project and add the appropriate import statements to the top of your code.  See also, https://github.com/ziminji/objective-c-sql-query-builder/wiki
