### ISSUE TITLE
Works on iOS 4

### ISSUE THREAD

**Issue by hffmnn** [ziminji/objective-c-sql-query-builder#5]
This is more a feedback than an issue:

As far as I can tell, objective-c-sql-query-builder builds fine even when the deployment target is set to iOS 4. I also tested on Hardware (an iPhone 3G) with iOS 4.2.1 and it works. Looks like it does not use any ARC iOS 5 specialities like weak... so I think you could change from iOS 5 to iOS 4 in your description.

**Comment by ziminji** [comment]
Many thanks for testing this SQLite 3 querying building library on devices running iOS 4.  I made the change in the project's description.
