### ISSUE TITLE
Issues with null values on ORM...

### ISSUE THREAD

**Issue by MrLuis** [ziminji/objective-c-sql-query-builder#6]
If a record has been inserted leaving a field with null value, the query function crash the application....

```
ZIMOrmSelectStatement *select = [[ZIMOrmSelectStatement alloc] initWithModel: [Song class]];
Library = [select query];   <--- crash happens here!
```

**Comment by MrLuis** [comment]
error message:
2012-04-08 05:12:14.506 IProj[15054:707] 1: <null>
2012-04-08 05:12:29.973 IProj[15054:707] -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x3f15d5e0
2012-04-08 05:12:29.975 IProj[15054:707] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull isEqualToString:]: unrecognized selector sent to instance 0x3f15d5e0'
**\* First throw call stack:

**Comment by MrLuis** [comment]
Actually I was wrong, the problem is when reading the value of an NSString field...

   cell.textLabel.text = song.Title;

I'm trying to analyze the value before assignment, but no success so far... it seems like the NSString was never created.

I'm trying the following code with no success... (the if statement always return false)
    if (song.Title == NULL) 
            song.Title = @" sdf";

**Comment by MrLuis** [comment]
Interesting notes...
- The problem only happen when I'm filling up a TableView... if I assign it to lets say UIText, it work fine!
- if I change the declaration from
  @property (Strong, nonatomic) NSString *Title;
  to
    @property (retain, nonatomic) NSString *Title;
  
  the problem seems to go away...  I'm new to Object-C, so I'm not sure the implications of that change...  but so far so good!

If this is a suitable solution, then we might want to change the example (Sample Model).

**Comment by ziminji** [comment]
Is your project utilizing Automatic Reference Counting (ARC)?  If changing a property to retain fixes the problem, I suspect that your problem is not with this library but that your project is not utilizing ARC.  This library will only work with projects that take advantage of ARC.  Try converting your project to use ARC.  Go to Edit >> Refactor >> Convert to Objective-C ARC... and follow the steps in the wizard.

**Comment by MrLuis** [comment]
You were right, I was not under ARC... did the process (had to fix up a few "weak" properties and done...

Interesting enough, after converting I had the error again!!! for some weird reason ARC removed most of my retain, I had to manually add those on my ZIMOrmModel class.

So far so good!!!

Tks 4 ur help!

**Comment by ziminji** [comment]
With ARC, you do NOT use retain, release, or autorelease.  Converting to using ARC, you don't have to worry about that stuff anymore.  Garbage collection is handled now automatically.
