### ISSUE TITLE
Delete statement not working out of [connection execute]

### ISSUE THREAD

**Issue by MrLuis** [ziminji/objective-c-sql-query-builder#9]
Hi, my code intent to remove some records out of a table by calling [connection execute]... however even when the statement execute with no error (and actually returns 1), the record is still there.  Am I missing something?

I try by using a begin/commit transaction, and still have the same result.

Code:
        ZIMDbConnection *connection = [[ZIMDbConnection alloc] initWithDataSource: @"dblitedb"];  
        NSString *Qry= @"DELETE FROM EventSongs";
        Qry =[Qry stringByAppendingFormat:@" Where pk=%@;", [song valueForKey:@"pk" ] ];
        NSLog(Qry);
        [connection beginTransaction];
        NSNumber *RetCount = [connection execute:Qry];
        NSLog(@"Records deleted! %@",RetCount);
        [connection commitTransaction];

Log:
2012-04-18 02:35:38.282 IMusicChords[28633:707] DELETE FROM EventSongs Where pk=13;
2012-04-18 02:35:38.285 IMusicChords[28633:707] Records deleted! 1

**Comment by ziminji** [comment]
I ran the following code and everything works fine:

```
NSString *statement = nil;

ZIMDbConnection *connection = [[ZIMDbConnection alloc] initWithDataSource: @"live"];

ZIMSqlCreateTableStatement *create = [[ZIMSqlCreateTableStatement alloc] init];
[create table: @"Customer"];
[create column: @"pk" type: ZIMSqlDataTypeInteger defaultValue: ZIMSqlDefaultValueIsAutoIncremented];
[create column: @"name" type: ZIMSqlDataTypeVarChar(35)];
statement = [create statement];
NSLog(@"%@", statement);
[connection execute: statement];

ZIMSqlInsertStatement *insert = [[ZIMSqlInsertStatement alloc] init];
[insert into: @"Customer"];
[insert column: @"name" value: @"Ziminji"];
statement = [insert statement];
NSLog(@"%@", statement);
[connection execute: statement];

NSArray *records = nil;

records = [connection query: @"SELECT * FROM [Customer];"];
for (NSDictionary *row in records) {
    NSLog(@"pk: %@", [row objectForKey: @"pk"]);
    NSLog(@"name: %@", [row objectForKey: @"name"]);
}

ZIMSqlDeleteStatement *sql = [[ZIMSqlDeleteStatement alloc] init];
[sql table: @"Customer"];
[sql where: @"name" operator: ZIMSqlOperatorEqualTo value: @"Ziminji"];
statement = [sql statement];
NSLog(@"%@", statement);
[connection execute: statement];

records = [connection query: @"SELECT * FROM [Customer];"];
for (NSDictionary *row in records) {
    NSLog(@"pk: %@", [row objectForKey: @"pk"]);
    NSLog(@"name: %@", [row objectForKey: @"name"]);
}

[connection close];
```

I got the following output:

2012-04-20 22:16:35.220 QueryBuilder[2194:f803] DROP TABLE [Customer];
2012-04-20 22:16:35.226 QueryBuilder[2194:f803] CREATE TABLE [Customer]([pk] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [name] VARCHAR%2835%29);
2012-04-20 22:16:35.231 QueryBuilder[2194:f803] INSERT INTO [Customer]([name]) VALUES ('Ziminji');
2012-04-20 22:16:35.236 QueryBuilder[2194:f803] pk: 1
2012-04-20 22:16:35.238 QueryBuilder[2194:f803] name: Ziminji
2012-04-20 22:16:35.239 QueryBuilder[2194:f803] DELETE FROM [Customer] WHERE [name] = 'Ziminji';

Based on the code you posted, it looks like you are expecting a "count"; however, [connection execute: Qry] does not return a count but rather whether the delete was successful.  Treat the result as a boolean not as a count.

**Comment by MrLuis** [comment]
Right on point sir!!!

I utilized ur delete example and worked as expected!

Tks!

```
   /* new code*/
     ZIMDbConnection *connection = [[ZIMDbConnection alloc] initWithDataSource: @"dbMusicChords"];    
    ZIMSqlDeleteStatement *sql = [[ZIMSqlDeleteStatement alloc] init];
    [sql table: @"EventSongs"];
    [sql where: @"pk" operator: ZIMSqlOperatorEqualTo value:[song valueForKey:@"pk" ]];
    NSString *statement = [sql statement];
    NSLog(@"%@", statement);
    [connection execute: statement];            

    /* Old code
    ZIMDbConnection *connection = [[ZIMDbConnection alloc] initWithDataSource: @"dbMusicChords"];    
    NSString *Qry=
    @"DELETE FROM EventSongs";
    Qry =[Qry stringByAppendingFormat:@" Where pk=%@;", [song valueForKey:@"pk" ] ];
    NSLog(Qry);
    [connection beginTransaction];
    NSNumber *RetCount = [connection execute:Qry];
    NSLog(@"Records deleted! %@",RetCount);
    [connection commitTransaction];
    */
```
